apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pizza
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: pizza/frontend:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pizza
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    run: frontend