apiVersion: apps/v1
kind: Deployment
metadata:
  name: toppings
  namespace: pizza
spec:
  selector:
    matchLabels:
      run: toppings
  replicas: 1
  template:
    metadata:
      labels:
        run: toppings
    spec:
      containers:
      - name: toppings
        image: pizza/toppings:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT
          value: "true"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"

---

apiVersion: v1
kind: Service
metadata:
  name: toppings
  namespace: pizza
spec:
  ports:
  - port: 80
  selector:
    run: toppings